apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ${{ values.component_id }}
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
  project: default  
  source:
    directory:
      jsonnet: {}
      recurse: true 
    path: apps/${{ values.component_id }}
    repoURL: git@github.com:in-the-keyhole/keyhole-gitops.git
    targetRevision: HEAD
  syncPolicy: 
    automated:
      prune: true