# {% set generated_name =  [values.component_id, '-', values.env] | join %}
# {% set bucket_name =  [generated_name,'-', (range(1000)|random)] | join %}

---
apiVersion: cloudfront.keyholesoftware.com/v1alpha1
kind: Distribution
metadata:
  namespace: default
  name: ${{ component_id }}
spec:
  parameters:
    region: us-east-2
    dnsSuffix: keyhole.institute
  compositionRef:
    name: cloudfront-distribution