---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: keyhole-software
  description: Keyhole Software

  links:
    - url: http://keyholesoftware.com/
      title: Website
spec:
  type: organization
  profile:
    displayName: Keyhole Software
    email: jniswonger@keyholesoftware.com
    # picture: https://avatars.dicebear.com/api/identicon/info@example.com.svg?background=%23fff&margin=25
  children: [developers, platform-engineering]

---
apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: teams
  description: A collection of all Backstage example Groups
spec:
  targets:
    - ./platform-engineering.yaml
    - ./developers.yaml
    # - ./ops.yaml
    # - ./dba.yaml