---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: keyhole-developers
  description: Keyhole Developers

  links:
    - url: http://keyholesoftware.com/
      title: Website
spec:
  type: organization
  profile:
    displayName: Keyhole Software
    email: jniswonger@keyholesoftware.com
    # picture: https://avatars.dicebear.com/api/identicon/info@example.com.svg?background=%23fff&margin=25
  children: [team-a]
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: team-a
  description: Team A
spec:
  type: team
  profile:
    # Intentional no displayName for testing
    email: team-a@example.com
    picture: https://avatars.dicebear.com/api/identicon/team-a@example.com.svg?background=%23fff&margin=25
  parent: backstage
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: breanna.davison
spec:
  profile:
    # Intentional no displayName for testing
    email: breanna-davison@example.com
    picture: https://avatars.dicebear.com/api/avataaars/breanna-davison@example.com.svg?background=%23fff
  memberOf: [team-a]
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: janelle.dawe
spec:
  profile:
    displayName: Janelle Dawe
    email: janelle-dawe@example.com
    picture: https://avatars.dicebear.com/api/avataaars/janelle-dawe@example.com.svg?background=%23fff
  memberOf: [team-a]
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: nigel.manning
spec:
  profile:
    displayName: Nigel Manning
    email: nigel-manning@example.com
    picture: https://avatars.dicebear.com/api/avataaars/nigel-manning@example.com.svg?background=%23fff
  memberOf: [team-a]
# ---
# apiVersion: backstage.io/v1alpha1
# kind: Location
# metadata:
#   name: teams
#   description: A collection of all Backstage example Groups
# spec:
#   targets:
#     - ./engineering.yaml
#     - ./dev.yaml
#     - ./ops.yaml
#     - ./dba.yaml