---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: platform-engineering
  description: Platform Engineering
spec:
  type: team
  profile:
    # Intentional no displayName for testing
    email: platform-engineering@keyholesoftware.com
    picture: https://avatars.dicebear.com/api/identicon/platform-engineering@keyholesoftware.com.svg?background=%23fff&margin=25
  parent: keyhole-software
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: bob.thebuilder
spec:
  profile:
    # Intentional no displayName for testing
    email: bob@keyholesoftware.com
    picture: https://avatars.dicebear.com/api/avataaars/bob@keyholesoftware.com.svg?background=%23fff
  memberOf: [platform-engineering]
