name: Deploy
on:
  push:
    branches:
      - main
jobs:
  run:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: {% raw %}${{ secrets.AWS_ACCESS_KEY_ID }}{% endraw %}
      AWS_SECRET_ACCESS_KEY: {% raw %}${{ secrets.AWS_SECRET_ACCESS_KEY }}{% endraw %}
      AWS_DEFAULT_REGION: {% raw %}${{ secrets.AWS_DEFAULT_REGION }}{% endraw %}
    steps:
        - uses: actions/checkout@v3

        - uses: actions/setup-node@v3
          with:
            node-version: 18
            cache: 'yarn'

        - name: Install dependencies
          run: yarn --frozen-lockfile

        - name: Build
          run: yarn build

        - name: Deploy to S3 and Invalidate CloudFront Distribution
          uses: reggionick/s3-deploy@v3
          with:
            folder: build
            bucket: {% raw %}${{ secrets.S3_BUCKET }}{% endraw %}
            bucket-region: {% raw %}${{ env.AWS_DEFAULT_REGION }}{% endraw %}
            delete-removed: true
            dist-id: {% raw %}${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}{% endraw %}