name: Deploy
on:
  push:
    branches:
      - main
jobs:
  run:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
    steps:
        - uses: actions/checkout@v3

        - uses: actions/setup-node@v3
          with:
            node-version: 18
            cache: 'yarn'

        - name: Install dependencies
          run: yarn --frozen-lockfile

        - name: Build
          run: yarn build

        - name: Deploy to S3 and Invalidate CloudFront Distribution
          uses: reggionick/s3-deploy@v3
          with:
            folder: build
            bucket: ${{ secrets.S3_BUCKET }}
            bucket-region: ${{ secrets.AWS_DEFAULT_REGION }}
            delete-removed: true
            dist-id: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}